version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitor
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    # image: express-server_server
    build: .
    container_name: express-server
    ports:
      - 8000:3000