version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitor
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    container_name: express-server
    ports:
      - 8000:8000

  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #     container_name: react:prod
  #     ports: 
  #       - 3000:80
